// <auto-generated />
namespace Service.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUserSignUpActivityTimeAndAuthenticationCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUserSignUpActivityTimeAndAuthenticationCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201305191228411_AddUserSignUpActivityTimeAndAuthenticationCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
